services:
  kartappfe:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - kartapp-network

networks:
  kartapp-network:
